### ISSUE TITLE
Cannot install on android lollipop required sdk api 24

### ISSUE THREAD

**Issue by ghost** [reiryuki/Xperia-Music-Magisk-Module#1]
![Screenshot_2020-08-18-20-04-06](https://user-images.githubusercontent.com/37603562/90510749-13ae0a00-e18e-11ea-8df5-7afaa3b562e8.png)

**Comment by reiryuki** [comment]
Ah that's my fault, I'm wrong to type sdk, I'm sorry
I will update it soon
Thanks for report 🙏

**Comment by ghost** [comment]
> Ah that's my fault, I'm wrong to type sdk, I'm sorry
> I will update it soon
> Thanks for report 🙏

No problem 👍

**Comment by ghost** [comment]
@reiryuki question what's the difference of your module in this 
![Screenshot_2020-08-18-20-41-34](https://user-images.githubusercontent.com/37603562/90514105-4c041700-e193-11ea-897a-76555af6b6f2.png)

**Comment by reiryuki** [comment]
> @reiryuki question what's the difference of your module in this
> ![Screenshot_2020-08-18-20-41-34](https://user-images.githubusercontent.com/37603562/90514105-4c041700-e193-11ea-897a-76555af6b6f2.png)

That's not working in Android 10 because missing restricted privileged permission

v1.4 is ready to download now https://github.com/reiryuki/Xperia-Libraries-Magisk-Module/releases/tag/v1.4 👍 tell me if it working

**Comment by ghost** [comment]
Confirmed it's installing now I just need to reboot to confirm if this module really work 😅
![Screenshot_2020-08-18-20-59-30](https://user-images.githubusercontent.com/37603562/90515906-e06f7900-e195-11ea-918f-4c8238df11e6.png)

**Comment by ghost** [comment]
Why I cannot click sound effects? But using sony magisk module I can click it 🤔
![Screenshot_2020-08-18-21-04-21](https://user-images.githubusercontent.com/37603562/90516569-c5e9cf80-e196-11ea-9efd-bbbcc855f430.png)

**Comment by ghost** [comment]
> Why I cannot click sound effects? But using sony magisk module I can click it 🤔
> ![Screenshot_2020-08-18-21-04-21](https://user-images.githubusercontent.com/37603562/90516569-c5e9cf80-e196-11ea-9efd-bbbcc855f430.png)

So just need to uncheck clearaudio+ to use sound effects like viper4androoid or dolby atmos 😅

Closing.

**Comment by reiryuki** [comment]
> > Why I cannot click sound effects? But using sony magisk module I can click it 🤔
> > ![Screenshot_2020-08-18-21-04-21](https://user-images.githubusercontent.com/37603562/90516569-c5e9cf80-e196-11ea-9efd-bbbcc855f430.png)
> 
> So just need to uncheck clearaudio+ to use sound effects like viper4androoid or dolby atmos 😅
> 
> Closing.

Nice! Thanks for the trial 🙏... Report me if you face any problems with 🙏
